name: release

on:
  push:
    # tags:
    #   - 'v*.*.*'
    paths-ignore:
      - 'LICENCE'
      - '*.md'
    branches:
      - main
      - devel

env:
  APP_NAME: 'TorCI'
  NIM_VERSION: '1.6.0'
  MAINTAINER: 'Luca'
  DESC: 'Configuration Interface for TorBox'

jobs:
  build-artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - buster
          # - bullseye
        arch:
          - amd64
          - arm

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          dir=artifact/${{ matrix.dist }}/${{ matrix.arch }}/torci

          mkdir -p $dir

          # Set env
          ARCH=${{ matrix.arch }}

          docker build -t torci:release -f build/${{ matrix.dist }} build
          docker run --rm -v `pwd`:/src/torci -e ARCH=${{ matrix.arch }} torci:release

          # Move bin
          mv torci $dir

          # Copy resources
          cp -r public $dir/public
          cp torci.nimble torci.conf config.nims LICENCE $dir
          
          archive_name_amd64=torci-${{ matrix.dist }}_amd64.tar.gz
          archive_name_arm=torci-${{ matrix.dist }}_arm.tar.gz

          tar -czvf $archive_name_amd64 $dir
          
          tree
        shell: bash

  # create-release:
  #   needs: [build-artifact]
  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: ${{ github.ref }}
  #       body: |
  #         ${{ steps.Changelog.outputs.changelog }}
  #       draft: false
  #       prerelease: false