name: release

on:
  push:
    # tags:
    #   - 'v*.*.*'
    paths-ignore:
      - 'LICENCE'
      - '*.md'
    branches:
      - main
      - devel

env:
  APP_NAME: 'TorCI'
  NIM_VERSION: '1.6.0'
  MAINTAINER: 'Luca'
  DESC: 'Configuration Interface for TorBox'

jobs:
  build-artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist:
          - buster
          - bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          amd64_dir=artifact/${{ matrix.dist }}/amd64/torci
          arm_dir=artifact/${{ matrix.dist }}/arm/torci

          # mkdir -p amd64_dir
          # mkdir -p arm_dir

          docker build -t torci:release -f build/${{ matrix.dist }} build
          docker run --rm -v `pwd`:/src/torci torci:release

          # Copy resources
          cp public amd64_dir/public
          cp torci.nimble torci.conf config.nims LICENCE amd64_dir
          
          cp public arm_dir/public
          cp torci.nimble torci.conf config.nims LICENCE arm_dir

          archive_name_amd64=torci-${{ matrix.dist }}_amd64.tar.gz
          archive_name_arm=torci-${{ matrix.dist }}_arm.tar.gz

          tar -czvf $archive_name_amd64 amd64_dir
          tar -czvf $archive_name_arm arm_dir
          
          ls -lah | grep torci
        shell: bash

  # create-release:
  #   needs: [build-artifact]
  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     with:
  #       tag_name: ${{ github.ref }}
  #       release_name: ${{ github.ref }}
  #       body: |
  #         ${{ steps.Changelog.outputs.changelog }}
  #       draft: false
  #       prerelease: false